version: "3"
services:
  blog:
    build: .
    entrypoint: /bin/bash
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/blog
    ports:
      - "3005:3000"
    environment:
      - TRUSTED_IP="0.0.0.0"
      - RAILS_ENV=development
  tester:
    build: .
    command: guard --no-bundler-warning --no-interactions
    volumes:
      - .:/blog
    environment:
      - RAILS_ENV=development
